[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

# app-arch/unarr
# semi-dead upstream

["app-editors/AppFlowy-bin"]
source = "github"
github = "AppFlowy-IO/AppFlowy"
use_latest_release = true

["app-editors/cpeditor"]
source = "github"
github = "cpeditor/cpeditor"
use_latest_release = true

# app-editors/lapce
# only live available

# dev-python/PyQt5
# regex needed here

# dev-qt/qtwebkit
# semi-dead upstream

["dev-util/cargo-tauri"]
source = "github"
github = "https://github.com/tauri-apps/tauri"
use_latest_release = true
prefix = "tauri-v"

["dev-util/codelite"]
source = "github"
github = "eranif/codelite"
use_latest_release = true

["dev-util/rust-analyzer"]
source = "github"
github = "rust-analyzer/rust-analyzer"
use_latest_release = true
from_pattern = "(\\d+)-(\\d+)-(\\d+)"
to_pattern = "\\1\\2\\3"

["dev-util/xmake"]
source = "github"
github = "xmake-io/xmake"
use_latest_release = true

["dev-vcs/guitar"]
source = "github"
github = "soramimi/Guitar"
prefix = "v"

["kde-misc/plasma-applet-netspeed-widget"]
source = "github"
github = "dfaust/plasma-applet-netspeed-widget"
use_latest_tag = true
prefix = "v"

["media-libs/libvips"]
source = "github"
github = "libvips/libvips"
prefix = "v"

# media-plugins/osdlyrics
# TODO

["media-sound/netease-cloud-music-gtk"]
source = "github"
github = "gmg137/netease-cloud-music-gtk"
use_latest_release = true

["media-sound/termusic"]
source = "github"
github = "tramhao/termusic"
use_latest_release = true
prefix = "v"

["net-misc/prips"]
source = "regex"
url = "https://devel.ringlet.net/sysutils/prips/"
regex = "The current version of <strong>prips</strong> is <strong>([\\d.]+)</strong>"

["net-misc/termscp"]
source = "github"
github = "veeso/termscp"
prefix = "v"

["net-proxy/clash"]
source = "github"
github = "Dreamacro/clash"
use_latest_release = true
prefix = "v"

["net-proxy/clash-meta"]
source = "github"
github = "MetaCubeX/Clash.Meta"
use_latest_release = true
prefix = "v"

["net-proxy/clash-verge"]
source = "github"
github = "zzzgydi/clash-verge"
use_latest_release = true
prefix = "v"

["net-proxy/v2rayA"]
source = "github"
github = "v2rayA/v2rayA"
use_latest_release = true
prefix = "v"

# TODO
# ["sci-mathematics/yade"]
# source = "gitlab"
# gitlab = "yade-dev/trunk"
# use_latest_release = true

["www-apps/openvscode-server-bin"]
source = "github"
github = "gitpod-io/openvscode-server"
use_latest_release = true
prefix = "openvscode-server-v"

["x11-apps/keyd"]
source = "github"
github = "rvaiya/keyd"
use_latest_release = true
prefix = "v"
