[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

["app-editors/zed"]
source = "github"
github = "zed-industries/zed"
prefix = "v"
use_latest_release = true

["dev-python/pypinyin"]
source = "pypi"
pypi = "pypinyin"

["dev-util/cargo-about"]
source = "cratesio"
cratesio = "cargo-about"

["dev-util/tauri-cli"]
source = "github"
github = "tauri-apps/tauri"
use_latest_release = true
prefix = "tauri-cli-v"

["dev-vcs/guitar"]
source = "github"
github = "soramimi/Guitar"
prefix = "v"
use_latest_release = true

["games-arcade/osu-lazer"]
source = "github"
github = "ppy/osu"
use_latest_release = true

["games-util/watt-toolkit"]
source = "github"
github = "BeyondDimension/SteamTools"
use_latest_release = true

["kde-misc/plasma-applet-netspeed-widget"]
source = "github"
github = "dfaust/plasma-applet-netspeed-widget"
use_latest_tag = true
prefix = "v"

["media-plugins/waylyrics"]
source = "github"
github = "waylyrics/waylyrics"
prefix = "v"
use_latest_release = true

["media-sound/netease-cloud-music-gtk"]
source = "github"
github = "gmg137/netease-cloud-music-gtk"
use_latest_release = true

["media-sound/termusic"]
source = "github"
github = "tramhao/termusic"
use_latest_release = true
prefix = "v"

["net-misc/termscp"]
source = "github"
github = "veeso/termscp"
prefix = "v"
use_latest_release = true

["net-p2p/qbittorrent-enhanced"]
source = "github"
github = "c0re100/qBittorrent-Enhanced-Edition"
prefix = "release-"
use_latest_release = true
